version: '3.8'

services:
  postgresdb:
    build:
      context: ./images/postgresdb
#    image: postgres:14
    container_name: airflow-postgres
    hostname: postgresdb    
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 120
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '54321:5432'
      


