version: '3.4'

x-common:
  &common
#  image: apache/airflow:2.3.0
  build:

    context: .
    dockerfile: images/airflow/Dockerfile
  user: "${AIRFLOW_UID}:0"
  env_file: 
    - .env.airflow
  volumes:
    - ./images/airflow/dags:/opt/airflow/dags
    - ./images/airflow/logs:/opt/airflow/logs
    - ./images/airflow/plugins:/opt/airflow/plugins
    - /var/run/docker.sock:/var/run/docker.sock
# Project and script pathes
    #ssl
    - ./srv/nginx/certs/host.docker.internal.crt:/srv/https/host.docker.internal.crt
    - ./srv/nginx/certs/host.docker.internal.key:/srv/https/host.docker.internal.key
    # 012 
    - ./images/airflow/plsql012:/usr/local/airflow/sql
    # 041 ml BinhPhan didnot work
    #- ./ml/BinhPhan/scripts:/usr/local/airflow/scripts
    #- ./ml/BinhPhan/data:/usr/local/airflow/data    

x-depends-on:
  &depends-on
  depends_on:
#    postgres:
#      condition: service_healthy
    airflow-init:
      condition: service_completed_successfully

services:
  postgresdb:
#    build:
#      context: ./images/postgresdb
    image: postgres:14
#    container_name: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 120
    restart: unless-stopped
    env_file:
      - .env.airflow
    ports:
      - '54321:5432'
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./images/postgresdb/database_user.sql:/docker-entrypoint-initdb.d/database_user.sql
      - ./images/postgresdb/dwh_tables.sql:/docker-entrypoint-initdb.d/dwh_tables.sql
      - ./images/postgresdb/populate_tables.sql:/docker-entrypoint-initdb.d/populate_tables.sql      
      - ./images/postgresdb/northwind_ddl.sql:/docker-entrypoint-initdb.d/northwind01_ddl.sql
      - ./images/postgresdb/northwind_data_source.sql:/docker-entrypoint-initdb.d/northwind02_data_source.sql

  mssql:
      image: mcr.microsoft.com/mssql/server:latest
      container_name: docker-mssql
      environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=Th1sS3cret!
          - POSTGRES_DB=airflow
      ports:
          - 1433:1433

  scheduler:
    <<: [*common, *depends-on]
    container_name: airflow-scheduler
    command: scheduler
    restart: on-failure
    ports:
      - "8793:8793"

  webserver:
    <<: [*common, *depends-on]
    container_name: airflow-webserver
    restart: always
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
  
  airflow-init:
    <<: *common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
        
#  nifi:
#      image: apache/nifi:latest
#      environment:
#        - SINGLE_USER_CREDENTIALS_USERNAME=${SINGLE_USER_CREDENTIALS_USERNAME:-admin}
#        - SINGLE_USER_CREDENTIALS_PASSWORD=${SINGLE_USER_CREDENTIALS_PASSWORD:-admin}
#      ports:
#          - 8082:8080
#          - 8443:8443
#          - 8001:8000
#      volumes:
#          - ./images/nifi/mssql-jdbc-12.2.0.jre8.jar:/lib/jdbc/mssql-jdbc-12.2.0.jre8.jar    
#          - ./images/nifi/data:/mnt/data                  
volumes:
  postgres-data:        